version: "3"

services:

  app:
    image: quotesun/laravel:latest
    user: 1000:1000
    container_name: memoji-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - memoji

  nginx:
    image: nginx:alpine
    container_name: memoji-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - memoji

networks:
  memoji:
    driver: bridge
